title: alertingavian.dev
email: contact@alertingavian.dev
description: >-
  Mostly nothing.
baseurl: "/" 
url: "alertingavian.dev"
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    - { platform: mastodon,          user_url: "https://mastodon.lol/@AlertingAvian" }
    - { platform: github,         user_url: "https://github.com/AlertingAvian" }

# Build settings
theme: minima
plugins:
  - jekyll-feed

